# Generated by Django 6.0 on 2026-01-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('england_rugby', '0002_delete_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='address',
            new_name='message',
        ),
    ]
