# Generated by Django 6.0 on 2026-01-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('england_rugby', '0003_rename_address_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('content', models.TextField()),
                ('image_name', models.CharField(blank=True, default='default.jpg', help_text="Enter the image filename (eg 'squad-pic.jpg')", max_length=30)),
            ],
        ),
    ]
