# Generated by Django 6.0 on 2026-01-13 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('england_rugby', '0005_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtext',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
